version: '2'
services:
 manager_db:
  image: mariadb
  volumes: 
   - "./data/managerdb:/var/lib/mysql"
   - "./db_init:/docker-entrypoint-initdb.d"
  restart: always
  environment:
   MYSQL_ROOT_PASSWORD: 0000000
   MYSQL_DATABASE: managerpress 
   MYSQL_USER: managerpress
   MYSQL_PASSWORD: managerpress

 manager_web:
  build: ./web
  depends_on:
   - manager_db
  volumes:
   - "./data/myapp:/var/www/html"
   - "./data/dbbk:/dbbk"
   - "./data/weblog:/var/log/apache2"
  ports:
   - "8890:80"
  restart: always
  links:
   - manager_db

 pcap_tool:
  build: ./pcap
  depends_on:
   - manager_db
  volumes:
   - "./data/pcap:/pcap"
   - "./data/pcaplog:/var/log/proftpd"
  ports:
   - "21:21"
   - "20:20"
   - "2222:2222"
   - "2223:2223"
   - "2224:2224"
   - "2225:2225"
  restart: always
  links:
   - manager_db
